### ISSUE TITLE
Instagram Managed Source, By Location

### ISSUE THREAD

**Issue by alxtnr** [datasift/datasift-java#102]
Hi

I noticed the Instagram.addResource method uses the latitude instead of the distance when the type is set to location/area and no four square ID has been supplied:

`parameterSet.set("distance", lattitude);`

Also, the value variable is checked for null in the switch statement and an illegal argument exception is thrown.  The "by location" methods on the Instagram class all supply a null as the value param.

Thanks

Alex

**Comment by zcourts** [comment]
Hi Alex,
Thank you for the report. This has been fixed
