### ISSUE TITLE
Problem when stop pylon record

### ISSUE THREAD

**Issue by RafaelAlbani** [datasift/datasift-java#104]
Hi,

Since i updated the API version to 1.3 and the Java Library to 3.2.13, i have not been able to stop records with the method **datasift.pylon().stop(PylonRecordingId pylonRecordingId)**, i always receive the same message _com.datasift.client.exceptions.DataSiftException: id must be a valid id_.

I tried to stop the records directly making the call to the stop endpoint(https://api.datasift.com/v1.3/pylon/stop) using Curl and the records are stop without any problem.

I am passing the PylonRecordingId in this manner **new PylonRecordingId(record.getRecordingId())** as the parameter in the stop method.

Best Regards

**Comment by RafaelAlbani** [comment]
Hi, do you have any estimate of when a version of the library with this fix will be released?

Thanks

**Comment by zcourts** [comment]
Some minor changes are going in today. As well as https://github.com/datasift/datasift-java/pull/106
So I expect it to go today, if not early next week.

**Comment by RafaelAlbani** [comment]
Hi @zcourts and thanks for let me know.
