### ISSUE TITLE
IllegalStateException with Message “unexpected message type: UnpooledUnsafeDirectByteBuf” from Netty

### ISSUE THREAD

**Issue by michaelahlers** [datasift/datasift-java#47]
I consistently get the following exception (from an `ErrorListener#exceptionCaught(Throwable)` instance registered with `StreamingData`) immediately after subscribing.

```
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: UnpooledUnsafeDirectByteBuf
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:193) ~[netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:645) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:699) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:638) [netty-all-4.0.12.Final.jar:na]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:645) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.DefaultChannelHandlerContext.access$2000(DefaultChannelHandlerContext.java:29) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.DefaultChannelHandlerContext$WriteTask.run(DefaultChannelHandlerContext.java:906) [netty-all-4.0.12.Final.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) [netty-all-4.0.12.Final.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [netty-all-4.0.12.Final.jar:na]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
Caused by: java.lang.IllegalStateException: unexpected message type: UnpooledUnsafeDirectByteBuf
        at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:80) ~[netty-all-4.0.12.Final.jar:na]
        at io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:94) ~[netty-all-4.0.12.Final.jar:na]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) [netty-all-4.0.12.Final.jar:na]
        ... 12 common frames omitted
```

Workflow is very simple:
1. Compile a simple CSDL query.
2. Subscribe using the resulting `Stream` object.

And I never seem to get any results, even for interactions containing common terms. Also of possible interest, I get these shortly after:

```
java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_45]
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_45]
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_45]
    at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.7.0_45]
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.7.0_45]
    at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[netty-all-4.0.12.Final.jar:na]
```

Using 3.0.0-Beta1. Is this a problem in my environment or a bug with the library.

**Comment by perfectmight** [comment]
We had this problem too, here is the stack trace : 

Feb  9 11:35:41 datasift-nexamaster io.netty.handler.codec.EncoderEx  java.lang.IllegalStateException: unexpected message type: UnpooledUnsafeDirectByteBuf
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:193)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:241)
Feb  9 11:35:41 datasift-nexamaster at  io.higgs.ws.client.WebSocketStream.send(WebSocketStream.java:51)
Feb  9 11:35:41 datasift-nexamaster at  io.higgs.ws.client.WebSocketClientHandler.completeHandshake(WebSocketClientHandler.java:135)
Feb  9 11:35:41 datasift-nexamaster at  io.higgs.ws.client.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:75)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:990)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.ssl.SslHandler.decode(SslHandler.java:873)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
Feb  9 11:35:41 datasift-nexamaster Caused  by: java.lang.IllegalStateException: unexpected message type: UnpooledUnsafeDirectByteBuf
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:78)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:106)
Feb  9 11:35:41 datasift-nexamaster at  io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)

We usually have this problem after a couple of hours having our Datasift Streamer running.
Although, we are openning more than one stream at a time (for different clients).

We run the same code over two identical VMs on independant environements. One has low amount of streams(3) using one connection, the other has a high amount of streams(40) with multiple connections(2-3).

I took a look at the last 3 traces and (i'm probably wrong) I wonder if it could be related to multi-threading and the encoders (chunk vs initial state) ?

**Comment by zcourts** [comment]
Do you know if this happens while the client is attempting to reconnect?
Which version of the client are you using 3.x.x?
The latest release ( I think for the last 4/5 releases) the client puts up to 200 subscriptions on a single websocket connection, for every 200 it adds one more websocket connection.

It's hard to say what could cause this other than an attempt to reconnect and there's a race condition which results in a message being written before the pipeline is configured or written at the end of the pipeline. Either of those would result in the Netty stack you've posted

Does this consistently happen every couple of hours?

**Comment by perfectmight** [comment]
According to DataSiftConfig.java line 36, i have version 3.0.0 (http.userAgent("DataSift/" + versionPrefix + " Java/v3.0.0");)

Also, yes it happends everytime after a couple of hours. Each time we end up after a day or 2 to restart it.

I'll try to update the Datasift java api code and see if it solves the issue in the upcomming days !

Thank you !
